# Generated by Django 3.2.15 on 2022-12-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('unanswered_task', models.TextField()),
                ('count_correct_answer', models.IntegerField(blank=True, default=0)),
                ('count_wrong_answer', models.IntegerField(blank=True, default=0)),
                ('percent_correct_answer', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
