# Generated by Django 3.2.15 on 2022-12-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0003_auto_20221214_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='test_suit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quize.testsuit', verbose_name='Набор тестов'),
            preserve_default=False,
        ),
    ]
