# Generated by Django 3.2.6 on 2022-12-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_card', '0002_auto_20221218_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='date_use',
            field=models.DateTimeField(blank=True, verbose_name='Дата использования'),
        ),
    ]
