# Generated by Django 3.2.6 on 2022-12-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_card', '0006_alter_creditcard_date_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма'),
        ),
    ]
