# Generated by Django 3.2.6 on 2022-12-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_card', '0007_alter_creditcard_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
    ]
